import { IFCTextarea } from '@Components/Textarea/IFCTextarea.vue';
import { VALID_INPUT_TYPES, VALID_STATES, STATE_MAP } from '@Components/Input/config';
import IFCButton from '@Components/Button/IFCButton.vue';
import { IFCThemeProvider } from '@Components/ThemeProvider/IFCThemeProvider.vue';

/**
 * Next line disabled because this is not production code. this is development code.
 * So importing from devDeps is fine
 */
/* eslint-disable-next-line import/no-extraneous-dependencies */
import { action } from '@storybook/addon-actions';

export default {
  title: 'Presentational Components/Form Components/Textarea',
  component: IFCTextarea,
  parameters: {
    jest: ['IFCTextarea.spec.js'],
    docs: {
      description: {
        component: 'This textarea component provides a rich interface input for long form text',
      },
    },
  },
  argTypes: {
    dark: { control: { type: 'boolean', default: false } },
    type: { control: { type: 'select', options: VALID_INPUT_TYPES } },
    state: { control: { type: 'select', options: VALID_STATES } },
    label: {
      description: 'Slot for inserting HTML content into the label',
    },
    microcopy: {
      description: `Slot for inserting HTML content as help text, or error messages, under the input.
        This defaults to autogenerated helper text based on certain prop states like minlength, maxlength, etc.`,
    },
    endcap: {
      description: 'Slot for inserting HTML content as an endcap for the input',
    },
    'front-endcap': {
      description: 'Slot for inserting HTML content as a front endcap for the input',
    },
  },
};

const EXCLUDED_KEYS = ['dark', 'label', 'microcopy', 'endcap', 'front-endcap'];

const CodeFactory = (args) => `
<IFCThemeProvider :dark="${args.dark ?? false}">
  <IFCTextarea
   ${Object.entries(args).filter(
    ([key]) => !EXCLUDED_KEYS.includes(key),
  ).map(([key, value]) => `${`${typeof value !== 'string' ? ':' : ''}${key}`}="${value}"\n`).join('   ')}  >
    <template v-slot:label>
      ${args.label ?? '<!-- Label Content Here -->'}
    </template>
    <template v-slot:microcopy>
      ${args.microcopy ?? '<!-- Microcopy Content Here -->'}
    </template>
    <template v-slot:endcap>
        ${args.endcap ?? '<!-- Endcap Content Here -->'}
    </template>
    <template v-slot:front-endcap>
        ${args['front-endcap'] ?? '<!-- Front Endcap Content Here -->'}
    </template>
  </IFCTextarea>
</IFCThemeProvider>
`;

const Template = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { IFCTextarea, IFCThemeProvider },
  data() {
    return {
      internalValue: args.value,
    };
  },
  methods: {
    onFocus: action('@focus'),
    onBlur: action('@blur'),
    onChange: action('@change'),
    onInput: action('@input'),
  },
  template: `
  <IFCThemeProvider :dark="dark">
    <IFCTextarea
      @focus="onFocus"
      @blur="onBlur"
      @input="internalValue = $event; onInput($event);"
      @change="internalValue = $event; onChange($event);"
      :value="internalValue"
      v-bind="$props" >
      <template #label>
        {{label}}
      </template>
      <template #microcopy>
        {{microcopy}}
      </template>
    </IFCTextarea>
  </IFCThemeProvider>
  `,
});

export const Text = Template.bind({});
Text.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: '',
};
Text.parameters = {
  docs: {
    source: {
      code: CodeFactory(Text.args),
    },
  },
};

export const LongLabel = Template.bind({});
LongLabel.args = {
  name: 'textInput',
  label: 'This is an input with an extraordinarily long label. Unlikely to ever to exist but oh well',
  state: STATE_MAP.default,
  value: '',
};
LongLabel.parameters = {
  docs: {
    source: {
      code: CodeFactory(LongLabel.args),
    },
  },
};

export const Placeholder = Template.bind({});
Placeholder.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: '',
  placeholder: 'Placeholder defined',
};
Placeholder.parameters = {
  docs: {
    source: {
      code: CodeFactory(Placeholder.args),
    },
  },
};

export const Disabled = Template.bind({});
Disabled.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: '',
  disabled: true,
};
Disabled.parameters = {
  docs: {
    source: {
      code: CodeFactory(Disabled.args),
    },
  },
};

export const Readonly = Template.bind({});
Readonly.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: 'Readonly text',
  readonly: true,
};
Readonly.parameters = {
  docs: {
    source: {
      code: CodeFactory(Readonly.args),
    },
  },
};

export const Error = Template.bind({});
Error.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.error,
  value: '',
};
Error.parameters = {
  docs: {
    source: {
      code: CodeFactory(Error.args),
    },
  },
};

export const Success = Template.bind({});
Success.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.success,
  value: '',
};
Success.parameters = {
  docs: {
    source: {
      code: CodeFactory(Success.args),
    },
  },
};

export const DarkMode = Template.bind({});
DarkMode.args = {
  name: 'textInput',
  label: 'Text Input',
  value: '',
  dark: true,
};
DarkMode.parameters = {
  backgrounds: {
    default: 'Dark Mode',
  },
  docs: {
    source: {
      code: CodeFactory(DarkMode.args),
    },
  },
};

export const Microcopy = Template.bind({});
Microcopy.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: '',
  microcopy: 'This can be a help message or an error message',
};
Microcopy.parameters = {
  docs: {
    source: {
      code: CodeFactory(Microcopy.args),
    },
  },
};

const AutoTemplate = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { IFCTextarea, IFCThemeProvider },
  data() {
    return {
      internalValue: args.value,
    };
  },
  methods: {
    onFocus: action('@focus'),
    onBlur: action('@blur'),
    onChange: action('@change'),
    onInput: action('@input'),
  },
  template: `
  <IFCThemeProvider>
    <IFCTextarea
      @focus="onFocus"
      @blur="onBlur"
      @input="onInput($event); internalValue = $event"
      @change="onChange"
      :value="internalValue"
      v-bind="$props" >
      <template #label>
        {{label}}
      </template>
    </IFCTextarea>
  </IFCThemeProvider>
  `,
});

export const AutomaticMicrocopy = AutoTemplate.bind({});
AutomaticMicrocopy.args = {
  name: 'textInput',
  label: 'Try typing into this',
  state: STATE_MAP.default,
  value: '',
  autocomplete: 'off',
  maxlength: 8,
  minlength: 4,
};
AutomaticMicrocopy.parameters = {
  docs: {
    source: {
      code: CodeFactory(AutomaticMicrocopy.args),
    },
  },
};

const CappedTemplate = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { IFCTextarea, IFCButton, IFCThemeProvider },
  data() {
    return {
      internalValue: args.value,
    };
  },
  methods: {
    onFocus: action('@focus'),
    onBlur: action('@blur'),
    onChange: action('@change'),
    onInput: action('@input'),
  },
  template: `
  <IFCThemeProvider>
    <IFCTextarea
      @focus="onFocus"
      @blur="onBlur"
      @input="onInput($event); internalValue = $event"
      @change="onChange"
      :value="internalValue"
      v-bind="$props" >
      <template #label>
        {{label}}
      </template>
      <template #microcopy>
        {{microcopy}}
      </template>
      <template #endcap>
      <IFCButton variant="primary" endcap>Endcap Button</IFCButton>
      </template>
    </IFCTextarea>
  </IFCThemeProvider>
  `,
});

export const EndCapContent = CappedTemplate.bind({});
EndCapContent.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: '',
  endcap: `
    <IFCButton variant="primary" endcap>Endcap Button</IFCButton>
  `,
};

EndCapContent.parameters = {
  docs: {
    source: {
      code: CodeFactory(EndCapContent.args),
    },
  },
};

const FrontCappedTemplate = (args, { argTypes }) => ({
  props: Object.keys(argTypes),
  components: { IFCTextarea, IFCButton, IFCThemeProvider },
  data() {
    return {
      internalValue: args.value,
    };
  },
  methods: {
    onFocus: action('@focus'),
    onBlur: action('@blur'),
    onChange: action('@change'),
    onInput: action('@input'),
  },
  template: `
  <IFCThemeProvider>
    <IFCTextarea
      @focus="onFocus"
      @blur="onBlur"
      @input="onInput($event); internalValue = $event"
      @change="onChange"
      :value="internalValue"
      v-bind="$props" >
      <template #label>
        {{label}}
      </template>
      <template #microcopy>
        {{microcopy}}
      </template>
      <template #front-endcap>
      <IFCButton variant="primary" endcap>Endcap Button</IFCButton>
      </template>
    </IFCTextarea>
  </IFCThemeProvider>
  `,
});

export const FrontEndCapContent = FrontCappedTemplate.bind({});
FrontEndCapContent.args = {
  name: 'textInput',
  label: 'Text Input',
  state: STATE_MAP.default,
  value: '',
  'front-endcap': '<IFCButton variant="primary" endcap>Endcap Button</IFCButton>',
};
FrontEndCapContent.parameters = {
  docs: {
    source: {
      code: CodeFactory(FrontEndCapContent.args),
    },
  },
};
