<template>
  <div class="IFCTable">
    <div class="IFCTable__twoColumnArea">
      <slot name="title">

      </slot>

      <slot name="configuration">
        <div class="IFCTable__configurationSpacer">
          <IFCSpacingSelector
            v-if="!hideSpacing"
            :sizes="sizes"
            :value="sizing"
            @sizing="$emit('sizeChange', $event)"/>
          <IFCButton
            v-if="!hideFilters"
            @click="showFilters = true"
            variant="info">
            <FilterIcon />
            Filters
          </IFCButton>
        </div>
      </slot>
    </div>
    <IFCCard
        class="IFCTable__activeFilters"
        :containsButtons="false"
        justify="flex-start"
        v-if="!hideActiveFilters">
        <template #title>
          <IFCSpan>Active Filters</IFCSpan>
        </template>
        <template #body>
          <slot name="activeFilters">
            <IFCSpan></IFCSpan>
          </slot>
        </template>
      </IFCCard>
    <div class="IFCTable__tableContainer">
      <table :class="computedTableClass">
        <thead>
          <slot name='headers'>
            <tr>
              <IFCTableHeader
                v-for="({key, text}) in autogeneratedHeaders"
                :grid="grid"
                :textAlign="textAlign"
                :sizing="sizing"
                :fitContent="computeFitContent(key)"
                :resizeable="resizeable"
                :interactive="computeInteractive(false, true, key)"
                :sortable="computeSortable(key)"
                :sortDirection="computeSortDirection(key)"
                :activelySorted="computeActivelySortedHeader(key)"
                @click="computeInteractive(false, true, key) ? $emit('click', key) : ''"
                @sort="$emit('sort', {key, sortDirection: computeSortDirection(key)})"
                @hover="$emit('hover', key)"
                :key="key">
                <slot name="header" :column="{key, text}">
                  {{text}}
                </slot>
              </IFCTableHeader>
              <IFCTableHeader
                v-if="showActions"
                textAlign="center"
                :grid="grid"
                :sizing="sizing"
                fitContent
                >
                  Actions
              </IFCTableHeader>
            </tr>
          </slot>
        </thead>
        <tbody :class="computedTbodyClass">
          <slot name="body">
            <tr
              v-for="(item, index) in items"
              :key="typeof defineKey === 'function' ? defineKey(item) : index">
              <IFCTableCell
                v-for="({ key }) in autogeneratedHeaders"
                :interactive="computeInteractive(item, false, key)"
                @click="computeInteractive(item, false, key) ? $emit('click', key) : ''"
                :textAlign="textAlign"
                :grid="grid"
                :sizing="sizing"
                :key="`${typeof defineKey === 'function' ? defineKey(item) : index}-${key}`">
                <slot name='cell' :item="{item, key}">
                  {{item[key]}}
                </slot>
              </IFCTableCell>
              <IFCTableCell
                v-if="showActions"
                :grid="grid"
                :sizing="sizing"
                textAlign="center"
                >
                  <template #external-content>
                    <ActionsContainer>
                      <IFCActionsDropdown
                        @action="$emit('action', {action: $event, item})"
                        :actions="actions"
                      />
                    </ActionsContainer>
                  </template>
              </IFCTableCell>
            </tr>
          </slot>
        </tbody>
      </table>
    </div>
    <div class="IFCTable__twoColumnArea">
      <IFCPageSizeSelector
        v-if="!hidePagination && !hidePaginationSizeControls"
        @change="$emit('pageSize', $event)"
        :value="resultsPerPage"
        :pageSizes="pageSizes" />
      <IFCPageSelector
        v-if="!hidePagination"
        @change="$emit('pageChange', $event)"
        :value="page"
        :pages="pages" />
    </div>
    <IFCModal
        v-if='!hideFilters'
        :id="`FilterModal-${_uid}`"
        :show="showFilters"
        @toggle="showFilters = false"
        title="Table Filters"
        modalDescription="Table Filters"
        :hideFooter="true"
        >
          <slot name="filters"></slot>
      </IFCModal>
  </div>
</template>

<script>
import { IFCModal } from '@Components/Modal/IFCModal.vue';
import { IFCButton } from '@Components/Button/IFCButton.vue';
import { convertToTitleCase } from '@Components/utils.js';
import { IFCPageSizeSelector } from '@Components/Pagination/IFCPageSizeSelector/IFCPageSizeSelector.vue';
import { IFCPageSelector } from '@Components/Pagination/IFCPageSelector/IFCPageSelector.vue';
import { IFCCard } from '@Components/Card/IFCCard.vue';
import { StringReplaceAllPolyfill } from '@Components/StringReplaceAllPolyfill.js';
import { IFCSpan } from '@Components/Text/IFCSpan.vue';
import { IFCTableCell } from './TableCell/IFCTableCell.vue';
import { IFCTableHeader } from './TableHeader/IFCTableHeader.vue';
import { IFCActionsDropdown } from './ActionsDropdown/IFCActionsDropdown.vue';
import { IFCSpacingSelector } from './SpacingSelector/IFCSpacingSelector.vue';
import { FilterIcon } from './icons/FilterIcon.vue';

export const IFCTable = {
  components: {
    IFCTableHeader,
    IFCTableCell,
    IFCActionsDropdown,
    IFCButton,
    FilterIcon,
    IFCSpacingSelector,
    IFCPageSizeSelector,
    IFCPageSelector,
    IFCModal,
    IFCCard,
    IFCSpan,
  },
  data() {
    return {
      showFilters: false,
    };
  },
  props: {

    /**
     * Hide the active filters panel
     */
    hideActiveFilters: {
      type: Boolean,
      default: false,
    },

    /**
     * Hide the spacing selection panel
     */
    hideSpacing: {
      type: Boolean,
      default: false,
    },

    /**
     * Hide the pagination controls
     */
    hidePagination: {
      type: Boolean,
      default: false,
    },

    /**
     * Hide just the pagination size controls
     */
    hidePaginationSizeControls: {
      type: Boolean,
      default: false,
    },

    /**
     * Hide the filters panel and the filter button.
     */
    hideFilters: {
      type: Boolean,
      default: false,
    },

    /**
     * How to text align the cells
     */
    textAlign: {
      type: String,
      default: 'left',
    },

    /**
     * Whether to show the actions column
     */
    showActions: {
      type: Boolean,
      default: false,
    },

    /**
     * What actions should be available for each row. Should be an array of strings that describe the verb.
     */
    actions: {
      type: Array,
      default() {
        return [];
      },
      validator(value) {
        return value.filter((e) => typeof e !== 'string').length === 0;
      },
    },

    /**
     * Whether the table should be condensed or not
     */
    sizing: {
      type: String,
      default: 'regular',
    },

    /**
     * What page sizes there are available. Should be array of numbers.
     */
    pageSizes: {
      type: Array,
      validator(value) {
        return !value.some((v) => Number.isNaN(Number(v)));
      },
      default() {
        return [
          25,
          50,
          100,
        ];
      },
    },

    /**
     * Current page size
     */
    resultsPerPage: {
      type: Number,
      default: 25,
    },

    /**
     * The current page in a paginated list
     */
    page: {
      type: Number,
      default: 1,
    },

    /**
     * The pages to choose from for pagination
     */
    pages: {
      type: [Array, Number],
      default: 1,
      validator(value) {
        return (Array.isArray(value) && !value.some((v) => Number.isNaN(Number(v)))) || !Number.isNaN(Number(value));
      },
    },

    /**
     * What sizing options there are. These should match the options in the theme.
     */
    sizes: {
      type: Array,
      validator(value) {
        return !value.some((v) => typeof v !== 'string');
      },
      default() {
        return [
          'condensed',
          'regular',
          'relaxed',
        ];
      },
    },

    /**
     * How the autodisplayer should key each row. Accepts one argument which is the item being iterated at the time
     */
    defineKey: {
      type: Function,
      required: false,
    },

    /**
     * Compute whether this header is sortable. Accepts one argument which is the key for that header.
     * Returns boolean.
     */
    computeSortable: {
      type: Function,
      /**
       * Disabled because we want the var there for documentation purposes.
       */
      /* eslint-disable-next-line no-unused-vars */
      default: (key) => false,
    },

    /**
     * Compute whether this sortable header's sort direction. Accepts one argument which is the key for that header.
     * Should return 'ascending' or 'descending'
     */
    computeSortDirection: {
      type: Function,
      /**
       * Disabled because we want the var there for documentation purposes.
       */
      /* eslint-disable-next-line no-unused-vars */
      default: (key) => 'descending',
    },

    /**
     * Compute whether this column should shrink to fit content
     */
    computeFitContent: {
      type: Function,
      /**
       * Disabled because we want the var there for documentation purposes.
       */
      /* eslint-disable-next-line no-unused-vars */
      default: (key) => false,
    },

    /**
     * Compute whether this sortable header is the actively sorted header.
     * Accepts one argument which is the key for that header. Returns boolean for whether it is actively sorted or not
     */
    computeActivelySortedHeader: {
      type: Function,
      /**
       * Disabled because we want the var there for documentation purposes.
       */
      /* eslint-disable-next-line no-unused-vars */
      default: (key) => false,
    },

    /**
     * Compute whether this cell is interactive. Accepts 3 arguments. First argument will be the item for
     * the cell or false if its a header, the second argument will be true when the cell is a header,
     * false when the cell is a td.
     * The third argument is the key for that column.
     */
    computeInteractive: {
      type: Function,
      /**
       * Disabled because we want the var there for documentation purposes.
       */
      /* eslint-disable-next-line no-unused-vars */
      default: (item, isHeader, key) => false,
    },

    /**
     * Whether the table should be a grid
     */
    grid: {
      type: Boolean,
      default: false,
    },

    /**
     * Whether the columns should be resizable
     */
    resizeable: {
      type: Boolean,
      default: false,
    },

    /**
     * Whether the rows should be hoverable
     */
    hoverable: {
      type: Boolean,
      default: false,
    },

    /**
     * Whether the external perimeter of the table should be outlined.
     */
    outlined: {
      type: Boolean,
      default: false,
    },

    /**
     * Whether the table is striped
     */
    striped: {
      type: Boolean,
      default: false,
    },

    /**
     * The items to display
     */
    items: {
      type: Array,
      default() {
        return [];
      },
    },
  },
  mounted() {
    StringReplaceAllPolyfill();
  },
  methods: {
    convertToTitleCase,
    generatePossibleKeys(items) {
      const uniqueKeys = new Set(items.map((sys) => Object.keys(sys)).reduce((acc, cur) => [...acc, ...cur], []));
      return Array.from(uniqueKeys).map((key) => ({ key, text: this.convertToTitleCase(key) }));
    },
  },
  computed: {
    autogeneratedHeaders() {
      return this.generatePossibleKeys(this.items);
    },
    baseClass() {
      return 'IFCTable';
    },
    computedTableClass() {
      return {
        [`${this.baseClass}__table`]: true,
        [`${this.baseClass}__table--outlined`]: this.outlined,
      };
    },
    computedTbodyClass() {
      return {
        [`${this.baseClass}__tbody`]: true,
        [`${this.baseClass}__tbody--striped`]: this.striped,
        [`${this.baseClass}__tbody--hoverable`]: this.hoverable,
      };
    },
  },
};

export default IFCTable;

</script>

<style lang="scss">
@import './table.scss';
</style>
